# Generated by Django 4.1.4 on 2023-01-16 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='to_do_list',
            name='user',
        ),
    ]
